In [1]:
import numpy as np

In [4]:
a = np.array([2,6,3,7,8])

In [5]:
print(a)

[2 6 3 7 8]


In [6]:
type(a)

numpy.ndarray

In [8]:
a.ndim #몇 차원인지

1

In [9]:
a.shape #a 배열에 몇개의 원소가 있는지

(5,)

In [10]:
a.dtype

dtype('int32')

In [12]:
b = np.array([[1,2,3],[4,5,6]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b.shape #행, 열

(2, 3)

In [16]:
np.zeros(5) #0이 5개

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.full((2,3),3.14159)

array([[3.14159, 3.14159, 3.14159],
       [3.14159, 3.14159, 3.14159]])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.random.random()

0.6405040388750349

In [24]:
np.random.seed(1)

In [25]:
np.random.random()

0.417022004702574

In [26]:
np.random.random((3,3)) #(3,3)은 배열의 크기 => 3*3

array([[7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01],
       [3.45560727e-01, 3.96767474e-01, 5.38816734e-01]])

In [27]:
np.random.normal(0,1,(2,3))

array([[ 1.74481176, -0.7612069 ,  0.3190391 ],
       [-0.24937038,  1.46210794, -2.06014071]])

In [28]:
np.random.randint(1,7,10) #정수 난수를 만들어줌  #1부터 6까지 아무 숫자나 10개 알려줘

array([1, 6, 2, 2, 6, 2, 2, 1, 5, 2])

In [29]:
x = np.array([5,2,9,3,7])

In [31]:
y = np.array([[2,4,6],[1,3,5]])

In [32]:
x

array([5, 2, 9, 3, 7])

In [33]:
y

array([[2, 4, 6],
       [1, 3, 5]])

In [34]:
y[1,1]

3

In [35]:
x

array([5, 2, 9, 3, 7])

In [36]:
x[1:4]

array([2, 9, 3])

In [37]:
x[:]

array([5, 2, 9, 3, 7])

In [38]:
x[::2]

array([5, 9, 7])

In [39]:
y

array([[2, 4, 6],
       [1, 3, 5]])

In [40]:
y[1:2, 1:]

array([[3, 5]])

In [41]:
y[1,1:]

array([3, 5])

In [42]:
y[0,:]

array([2, 4, 6])

In [43]:
z = y[:,1]

In [44]:
z

array([4, 3])

In [46]:
z[1] = 10000

In [47]:
z

array([    4, 10000])

In [48]:
y

array([[    2,     4,     6],
       [    1, 10000,     5]])

In [49]:
a = np.arange(9)

In [50]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
a.shape

(9,)

In [52]:
type((9,))

tuple

In [53]:
a = np.arange(9).reshape((3,3)) #9개의 숫자를 만들어서 3*3 형태의 2차원으로 만든다

In [55]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
a.shape

(3, 3)

In [57]:
b = np.arange(5)

In [58]:
b.shape

(5,)

In [59]:
b = np.arange(5).reshape((1,5))

In [60]:
b

array([[0, 1, 2, 3, 4]])

In [61]:
b = np.arange(5).reshape((5,1))

In [62]:
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [63]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [65]:
a.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [70]:
a = np.array([1,2,3]); b = np.array([4,5,6])

In [72]:
a + b  #더하기를 해도 결합은 아님

array([5, 7, 9])

In [74]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [77]:
grid1 = np.ones((3,3))

In [78]:
grid1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
grid2 = np.full((3,3),2.)

In [81]:
grid2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [82]:
np.concatenate([grid1, grid2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [84]:
np.concatenate([grid1, grid2], axis=1)

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

In [85]:
x = np.arange(3,15,2)

In [86]:
x

array([ 3,  5,  7,  9, 11, 13])

In [87]:
a, b = np.split(x, [2]) #기준점이 2번째에서 잘림

In [89]:
a

array([3, 5])

In [90]:
b

array([ 7,  9, 11, 13])

In [94]:
x

array([ 3,  5,  7,  9, 11, 13])

In [95]:
a, b, c = np.split(x, [2,5])

In [96]:
a

array([3, 5])

In [97]:
b

array([ 7,  9, 11])

In [98]:
c

array([13])