In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 유방암(진단) 데이터셋

In [2]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data'
df = pd.read_csv(path, header=None)

In [3]:
df

0  1      2      3       4       5        6        7        8   \
0      842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [4]:
X = df.iloc[:, 2:].values #번호라 iloc

In [5]:
y = df.iloc[:,1]

In [7]:
y #M은 악성 B는 양성

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: 1, Length: 569, dtype: object

In [8]:
y = np.where(y == 'M', 1, 0) # y가 M이면 1 아니면 0

In [10]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, stratify = y, random_state = 1) #데이터 분할

## 파이프라인

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression

In [20]:
from sklearn.pipeline import make_pipeline

In [21]:
pipe = make_pipeline(StandardScaler(), PCA(n_components=2), LogisticRegression(random_state = 1))

In [22]:
type(pipe)

sklearn.pipeline.Pipeline

In [23]:
pipe.fit(X_train,y_train) #pipeline 안에 표준화가 이미 들어가있어서 표준화를 따로 안함

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('pca', PCA(n_components=2)),
                ('logisticregression', LogisticRegression(random_state=1))])

In [24]:
y_pred = pipe.predict(X_test)

In [25]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1])

In [26]:
y_test

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1])

In [27]:
pipe.score(X_test, y_test)

0.956140350877193

In [28]:
from sklearn.metrics import confusion_matrix

In [29]:
confusion_matrix(y_test, y_pred)  # confusion_matrix(실제값, 예측값)

# 71은 d를 d로 분류, 1은 m을 m으로 분류
# 4명은 진짜는 악성인데 머신러닝은 양성

array([[71,  1],
       [ 4, 38]], dtype=int64)

## 모델 튜닝과 교차검증

In [30]:
from sklearn.model_selection import cross_val_score

In [33]:
scores = cross_val_score(estimator = pipe, X = X_train, y = y_train, cv = 10, n_jobs = -1) 

# cv=> 데이터를 10등분
#n_jobs = 2 => 코어 2개 사용 ,-1이면 모든 코어 사용

In [34]:
scores

array([0.93478261, 0.93478261, 0.95652174, 0.95652174, 0.93478261,
       0.95555556, 0.97777778, 0.93333333, 0.95555556, 0.95555556])

In [35]:
np.mean(scores)

0.9495169082125603

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
for k in range(1,11):
    scores = cross_val_score(estimator = DecisionTreeClassifier(max_depth=k, random_state=1), 
                             X = X_train, y = y_train, 
                             cv = 5, n_jobs = -1) 
    val_score = np.mean(scores)
    print('max_depth: ' , k, val_score)

max_depth:  1 0.8813186813186814
max_depth:  2 0.9318681318681319
max_depth:  3 0.9296703296703297
max_depth:  4 0.9406593406593406
max_depth:  5 0.9384615384615385
max_depth:  6 0.9362637362637363
max_depth:  7 0.9406593406593406
max_depth:  8 0.9406593406593406
max_depth:  9 0.9406593406593406
max_depth:  10 0.9406593406593406


In [39]:
best_score = 0
for k in range(1,11):
    scores = cross_val_score(estimator = DecisionTreeClassifier(max_depth=k, random_state=1), 
                             X = X_train, y = y_train, 
                             cv = 5, n_jobs = -1) 
    val_score = np.mean(scores)
    print('max_depth: ' , k, val_score)
    if val_score > best_score:
        best_score = val_score
        best_param = {'max_depth' : k}

max_depth:  1 0.8813186813186814
max_depth:  2 0.9318681318681319
max_depth:  3 0.9296703296703297
max_depth:  4 0.9406593406593406
max_depth:  5 0.9384615384615385
max_depth:  6 0.9362637362637363
max_depth:  7 0.9406593406593406
max_depth:  8 0.9406593406593406
max_depth:  9 0.9406593406593406
max_depth:  10 0.9406593406593406


In [40]:
best_score

0.9406593406593406

In [41]:
best_param

{'max_depth': 4}

In [42]:
best_tree = DecisionTreeClassifier(**best_param)
# best_tree = DecisionTreeClassifier(max_depth = 4)

In [45]:
best_tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4)

In [46]:
best_tree.score(X_test, y_test)

0.9210526315789473

### 유방암 데이터에 대한 결정트리 모형 튜닝

In [47]:
from sklearn.model_selection import GridSearchCV

In [48]:
my_grid = {'max_depth' : range(1,11)}

In [50]:
gs = GridSearchCV(estimator = DecisionTreeClassifier(random_state=1),
                 param_grid = my_grid,
                 cv = 5,
                 n_jobs = -1)

In [51]:
gs.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=1), n_jobs=-1,
             param_grid={'max_depth': range(1, 11)})

In [52]:
gs.best_score_

0.9406593406593406

In [53]:
gs.best_params_

{'max_depth': 4}

### 유방암 데이터에 대한 SVC 모형 튜닝

In [56]:
from sklearn.svm import SVC
pipe_svc = make_pipeline(StandardScaler(), SVC(kernel='rbf', random_state=1))
p_list = [0.001,0.01,0.1,1.0,10.0,100.0]
param_grid = {'svc__C':p_list, 'svc__gamma':p_list}
gs = GridSearchCV(estimator=pipe_svc, param_grid=param_grid, scoring='accuracy', cv=5, n_jobs=-1)
gs.fit(X_train, y_train)
print(gs.best_params_) #{'svc__C': 10.0, 'svc__gamma': 0.01}
print(gs.score(X_test, y_test)) #0.9736

# 6개 (p_list)를 두번 돌려야 하니까 총 36개이고 {'svc__C': 10.0, 'svc__gamma': 0.01}이 베스트 값

{'svc__C': 10.0, 'svc__gamma': 0.01}
0.9736842105263158
