## Numpy 배열 연산

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
b = np.array([5,5,5])  # np.full 함수도 사용 사능

In [5]:
a + b

array([6, 7, 8])

In [6]:
(a + 1)

array([2, 3, 4])

In [7]:
(a + 1) ** 2

array([ 4,  9, 16], dtype=int32)

In [8]:
np.exp(a)  #익스포넨셜 값?

array([ 2.71828183,  7.3890561 , 20.08553692])

In [9]:
np.arange(3) + 5

array([5, 6, 7])

In [10]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [11]:
np.arange(3).reshape(3,1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

##  Numpy  배열 집계

In [12]:
np.random.seed(0)

In [13]:
x = np.random.random(10)

In [14]:
x

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [15]:
sum(x)

6.157662833145425

In [16]:
np.sum(x)

6.157662833145425

In [17]:
x.sum()

6.157662833145425

In [18]:
%time sum(np.random.random(10000))

Wall time: 995 µs


4962.657988754934

In [19]:
%timeit sum(np.random.random(10000))

797 µs ± 162 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
%timeit np.sum(np.random.random(10000))

76.8 µs ± 9.16 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
y = np.array([[1,2],[3,4]])

In [22]:
y

array([[1, 2],
       [3, 4]])

In [23]:
np.sum(y)

10

In [24]:
np.sum(y, axis = 0) # 열별 합(colum sum)

array([4, 6])

In [25]:
np.sum(y, axis = 1) # 행별 합

array([3, 7])

In [26]:
t = np.array([5,2,8,5,1])

In [27]:
np.max(t)

8

In [28]:
np.argmax(t)  #인덱스 값 8의 순서가 0,1,2 2번째라 2

2

In [29]:
t = np.array([5,2,8,5,1], dtype = np.float64)

In [30]:
t.dtype

dtype('float64')

In [31]:
t[0] = np.NaN

In [32]:
t

array([nan,  2.,  8.,  5.,  1.])

In [33]:
np.sum(t)

nan

In [34]:
np.nansum(t)  #nan = Not a Number #nansum은 nan 값 제외한 나머지

16.0

In [35]:
x = np.array([4,2,6,7,3.3])

In [36]:
z = (x - np.mean(x)) / np.std(x)

In [37]:
z

array([-0.25374507, -1.35698453,  0.84949438,  1.40111411, -0.63987888])

In [38]:
z.mean()

-4.4408920985006264e-17

In [39]:
z.std()

1.0

In [40]:
X = np.random.randint(0, 100, (10,2))

In [41]:
X

array([[89, 96],
       [20, 38],
       [45, 18],
       [51, 65],
       [90, 76],
       [ 7, 14],
       [34, 83],
       [95,  3],
       [35, 14],
       [86, 76]])

In [42]:
avgs = np.mean(X, axis = 0)

In [43]:
avgs

array([55.2, 48.3])

In [44]:
sds = np.std(X, axis = 0)

In [45]:
sds  # 표준편차

array([30.70439708, 32.74461788])

In [46]:
Z = (X - avgs) / sds

In [47]:
Z

array([[ 1.10081953,  1.45672795],
       [-1.14641561, -0.31455551],
       [-0.33219998, -0.92534291],
       [-0.13678823,  0.51000748],
       [ 1.13338816,  0.84594055],
       [-1.56980773, -1.04750039],
       [-0.69045485,  1.05971614],
       [ 1.29623128, -1.38343346],
       [-0.65788623, -1.04750039],
       [ 1.00311366,  0.84594055]])

## 비교, 마스크, 부울 로직

In [48]:
x = np.arange(7)

In [49]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [50]:
x < 3

array([ True,  True,  True, False, False, False, False])

In [52]:
np.where(x < 3, 1, 0) # x라는 배열의 각각의 원소에 대해서 그 원소가 3보다 작으면 1, 3보다 크거나 같으면 0

array([1, 1, 1, 0, 0, 0, 0])

In [55]:
x[x < 3]

array([0, 1, 2])

In [56]:
a = np.array([[0,1],[2,3]])

In [57]:
b = np.array([[1,1],[4,0]])

In [58]:
a

array([[0, 1],
       [2, 3]])

In [59]:
b

array([[1, 1],
       [4, 0]])

In [60]:
a @ b

array([[ 4,  0],
       [14,  2]])